version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - grouper
    - iface
    - interfacebloat
    - intrange
    - loggercheck
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - modernize
  settings:
    revive:
      severity: warning

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false