name: "Go Verify Build"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  GO_VER: 1.23.4

jobs:
  check-cyrillic-comments:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4
      - name: check cyrillic comments
        run: |
          grep --exclude-dir=".github" -I -r --color -n -E "[А-Яа-яЁё]+" . && exit 1 || exit 0

  validate-go:
    needs:
      - check-cyrillic-comments
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VER }}

      - name: check go.mod
        run: |
          go mod tidy
          git diff --exit-code go.mod

      - name: go fmt
        run: |
          go fmt ./...
          git diff --exit-code

  golangci-lint:
    needs:
      - validate-go
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VER }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
          args: --out-format=colored-line-number
          skip-cache: true
          problem-matchers: true

#  go-unit-test:
#    needs:
#      - golangci-lint
#    runs-on: 'ubuntu-22.04'
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-go@v5
#        with:
#          go-version: ${{ env.GO_VER }}
#
#      - name: unit test
#        run: |
#          go test -count 1 ./...
